<a href="https://colab.research.google.com/github/chaehyewon/2024-2-Deep-Learning-Application-Programming/blob/main/inclass/%EC%88%98_%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4%ED%95%99%EA%B3%BC_20232882_%EC%B1%84%ED%98%9C%EC%9B%90_3%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C_KNN(1%EC%B1%85).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### KNN(K-Nearest Neighbors)

#### import library

In [40]:
# library & data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import metrics
# from sklearn.datasets import load_iris
# iris = load_iris()

dataset = pd.read_csv('/content/sample_data/Data_all/Iris.csv')

#### search of data

In [41]:
dataset
#print(dataset)
#ataset.info()
#dataset.describe()
#dataset.head(5)
#dataset.tail()
#dataset.columns
#dataset.shape
#dataset.dtypes
#dataset.isnull().sum()

sepal-length  sepal-width  petal-length  petal-width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [42]:
# training과 test dataset 분리

X = dataset.iloc[0:, :-1].values  # 뒤에서 하나를 뺸 값을 가져와서 X 에 저장
y = dataset.iloc[:, 4].values     # 열은 앞에서 다섯 번쨰 값만 가져와서 y에 저장

#X.shape
#X
#y.shape
#y
#print(X)
#print(y)
print(X,y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

#### training dataset:80% / test dataset:20%

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)  # test dataset 20% 사용

#X_train.shape
#X_test.shape
#y_train.shape
y_test.shape


(30,)

In [44]:
# Data Standardization(표준화) : Feature의 범위가 다른 경우에만 사용
from sklearn.preprocessing import StandardScaler
s = StandardScaler()             # 특성 스케일링(scaling), 평균이 0, 표준편차가 1이 되도록 변환
s.fit(X_train)                   ## 교과서를 변경한 부분

X_train = s.transform(X_train)  # 훈련 데이터를 스케일링 처리
X_test = s.transform(X_test)    # 테스트 데이터를 스케일링 처리

#X_train
X_test

array([[-1.17055521,  0.05591011, -1.28966195, -1.44495916],
       [ 0.71490285, -0.17544208,  0.9475543 ,  0.75482941],
       [-0.22782618, -1.10085087, -0.17105383, -0.28036521],
       [-0.81703183, -0.86949867,  0.0526678 ,  0.2372321 ],
       [-1.5240786 ,  0.28726231, -1.34559236, -1.31555983],
       [-1.5240786 ,  0.05591011, -1.28966195, -1.31555983],
       [-0.10998505, -0.86949867,  0.72383268,  0.88422874],
       [ 0.9505851 ,  0.51861451,  1.05941511,  1.66062471],
       [-0.46350844,  0.9813189 , -1.40152277, -1.31555983],
       [-0.22782618, -0.40679428,  0.22045902,  0.10783277],
       [-1.05271408,  0.7499667 , -1.23373155, -1.05676118],
       [-0.93487295,  1.44402329, -1.28966195, -1.05676118],
       [ 0.1256972 , -0.17544208,  0.55604146,  0.75482941],
       [-1.05271408, -1.79490745, -0.28291464, -0.28036521],
       [ 0.1256972 , -2.02625965,  0.10859821, -0.28036521],
       [-1.5240786 ,  0.7499667 , -1.34559236, -1.18616051],
       [ 0.59706172,  0.

In [45]:
# create moder (KNN)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=50)               # k의 값 : 3,5,7,9,11,13,15...49
#y_train = y_train.astype(int)    # fiv type error
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=50)

In [46]:
# model accuracy
from sklearn import metrics
y_pred = knn.predict(X_test)
print("Accuracy: {}".format(metrics.accuracy_score(y_test, y_pred)))

Accuracy: 0.9


In [48]:
###################################################################
k = 10
acc_array = np.zeros(k)
for k in np.arange(1, k+1, 1):
    classifier = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    acc = metrics.accuracy_score(y_test, y_pred)
    acc_array[k-1] = acc

max_acc = np.amax(acc_array)
acc_list = list(acc_array)
k = acc_list.index(max_acc)
print("Accuarcy is", metrics.accuracy_score(y_test, y_pred), "for K-value", k)

Accuarcy is 0.9 for K-value 0
