<a href="https://colab.research.google.com/github/chaehyewon/2024-2-Deep-Learning-Application-Programming/blob/main/inclass/%EC%88%98_%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4%ED%95%99%EA%B3%BC_20232882_%EC%B1%84%ED%98%9C%EC%9B%90_3%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C_KNN(2%ED%99%9C%EC%9A%A9).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### KNN(K-Nearest Neighbors)

#### import library

In [1]:
# library & data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import metrics
# from sklearn.datasets import load_iris
# iris = load_iris()

dataset = pd.read_csv('/content/sample_data/Data_all/Iris.csv')

#### search of data

In [2]:
dataset
#print(dataset)
#ataset.info()
#dataset.describe()
#dataset.head(5)
#dataset.tail()
#dataset.columns
#dataset.shape
#dataset.dtypes
#dataset.isnull().sum()

sepal-length  sepal-width  petal-length  petal-width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
# training과 test dataset 분리

X = dataset.iloc[0:, :-1].values  # 뒤에서 하나를 뺸 값을 가져와서 X 에 저장
y = dataset.iloc[:, 4].values     # 열은 앞에서 다섯 번쨰 값만 가져와서 y에 저장

#X.shape
#X
#y.shape
#y
#print(X)
#print(y)
print(X,y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

#### training dataset:80% / test dataset:20%

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)  # test dataset 20% 사용

#X_train.shape
#X_test.shape
#y_train.shape
y_test.shape


(30,)

In [5]:
# Data Standardization(표준화) : Feature의 범위가 다른 경우에만 사용
from sklearn.preprocessing import StandardScaler
s = StandardScaler()             # 특성 스케일링(scaling), 평균이 0, 표준편차가 1이 되도록 변환
s.fit(X_train)                   ## 교과서를 변경한 부분

X_train = s.transform(X_train)  # 훈련 데이터를 스케일링 처리
X_test = s.transform(X_test)    # 테스트 데이터를 스케일링 처리

#X_train
X_test

array([[-1.72489452, -0.11643019, -1.4035695 , -1.32273616],
       [-1.49008188,  1.32891009, -1.57462062, -1.32273616],
       [ 0.97545084,  0.60623995,  1.10518032,  1.18419522],
       [ 0.7406382 , -0.11643019,  1.16219736,  1.31613898],
       [ 0.97545084,  0.12445986,  0.36395878,  0.26058892],
       [ 0.1536066 , -0.83910033,  0.76307807,  0.52447643],
       [-0.90305028,  1.08802004, -1.34655246, -1.32273616],
       [ 0.7406382 , -0.11643019,  0.99114623,  0.78836395],
       [-0.90305028,  1.81069018, -1.06146725, -1.05884865],
       [ 0.27101292, -0.59821028,  0.5350099 , -0.00329859],
       [ 0.97545084, -1.32088042,  1.16219736,  0.78836395],
       [ 0.1536066 , -2.04355056,  0.70606103,  0.39253268],
       [-1.13786292, -1.32088042,  0.42097582,  0.65642019],
       [-0.90305028,  1.08802004, -1.34655246, -1.19079241],
       [ 0.50582556, -1.80266052,  0.36395878,  0.12864516],
       [ 0.27101292, -0.11643019,  0.64904399,  0.78836395],
       [-0.19861236,  1.

In [6]:
# create moder (KNN)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=50)               # k의 값 : 3,5,7,9,11,13,15...49
#y_train = y_train.astype(int)    # fiv type error
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=50)

In [7]:
# model accuracy
from sklearn import metrics
y_pred = knn.predict(X_test)
print("Accuracy: {}".format(metrics.accuracy_score(y_test, y_pred)))

Accuracy: 0.8


In [22]:
###################################################################
k = 10
acc_array = np.zeros(k)
for k in np.arange(1, k+1, 1):
    classifier = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    acc = metrics.accuracy_score(y_test, y_pred)
    acc_array[k-1] = acc

max_acc = np.amax(acc_array)
acc_list = list(acc_array)
k = acc_list.index(max_acc)
print("Accuarcy is", metrics.accuracy_score(y_test, y_pred), "for K-value", k)

Accuarcy is 0.8666666666666667 for K-value 0


In [31]:
################################################################### 활용1
k = 20
acc_array = np.zeros(k)
for k in np.arange(1, k+1, 1):
    classifier = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    acc = metrics.accuracy_score(y_test, y_pred)
    acc_array[k-1] = acc

max_acc = np.amax(acc_array)
acc_list = list(acc_array)
k = acc_list.index(max_acc)
print("Accuarcy is", metrics.accuracy_score(y_test, y_pred), "for K-value", k)

Accuarcy is 0.9333333333333333 for K-value 0


In [9]:
################################################################### 활용2
k = 50
acc_array = np.zeros(k)
for k in np.arange(1, k+1, 5):
    classifier = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    acc = metrics.accuracy_score(y_test, y_pred)
    acc_array[k-1] = acc

max_acc = np.amax(acc_array)
acc_list = list(acc_array)
k = acc_list.index(max_acc)
print("Accuarcy is", metrics.accuracy_score(y_test, y_pred), "for K-value", k)

Accuarcy is 0.8 for K-value 0
